/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'rbalda' at '20/06/16 1:05' with Gradle 2.9
 *
 * @author rbalda, @date 20/06/16 1:05
 */
public class Prueba {
    public boolean someLibraryMethod() {
        return true;
    }
}
