import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'rbalda' at '20/06/16 1:05' with Gradle 2.9
 *
 * @author rbalda, @date 20/06/16 1:05 :) :(
 */
public class PruebaTest {
    @Test public void testSomeLibraryMethod() {
        Prueba classUnderTest = new Prueba();
        assertFalse("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
